//
// Created by hetto on 27.03.2026.
//

#ifndef LOXINTERPRETER_SCANNER_HPP
#define LOXINTERPRETER_SCANNER_HPP

enum TokenType {
    //SINGLE CHARACTER TOKENS
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_COMMA, TOKEN_DOT, TOKEN_MINUS,
    TOKEN_PLUS,
    TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_STAR,
    //ONE OR TWO CHARACTER TOKENS
    TOKEN_BANG, TOKEN_BANG_EQUAL,
    TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL,

    //LITERALS

    TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,

    //KEYWORDS
    TOKEN_AND, TOKEN_CLASS, TOKEN_ELSE, TOKEN_FALSE,
    TOKEN_FOR, TOKEN_FUN, TOKEN_IF, TOKEN_NIL, TOKEN_OR,
    TOKEN_PRINT, TOKEN_RETURN,
    TOKEN_SUPER, TOKEN_THIS, TOKEN_TRUE, TOKEN_VAR, TOKEN_WHILE,

    TOKEN_ERROR, TOEKN_EOF
};

struct Token {
    TokenType type;
    const char* start;
    int length;
    int line;
};


void initScanner(const char* source);

Token scanToken();


#endif //LOXINTERPRETER_SCANNER_HPP